export enum KeyboardKeys {
  TAB = 'Tab',
  SHIFT = 'Shift',
  ENTER = 'Enter',
  BLANK_SPACE = ' ',
  SPACE = 'Space',
  ESC = 'Esc',
  ESCAPE = 'Escape',
  UP = 'Up',
  DOWN = 'Down',
  LEFT = 'Left',
  RIGHT = 'Right',
  ARROW_UP = 'ArrowUp',
  ARROW_DOWN = 'ArrowDown',
  ARROW_LEFT = 'ArrowLeft',
  ARROW_RIGHT = 'ArrowRight',
  PAGE_UP = 'PageUp',
  PAGE_DOWN = 'PageDown',
  HOME = 'Home',
  END = 'End',
}
