name: Build and Test

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install Angular Cli
      - name: Install dependencies
        run: npm install -g @angular/cli

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Run unit tests
      - name: Run unit tests
        run: npm run test:coverage --watch=false --browsers=ChromeHeadless

      # 6. Build library
      - name: Build project
        run: ng build percy

      # 7. Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/
          
