name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install Angular Cli
      - name: Install Angular Cli
        run: npm install -g @angular/cli

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Run unit tests
      # - name: Run unit tests
      #   run: npm run test:coverage --watch=false --browsers=ChromeHeadless
      - name: Jest Code Coverage Report
        uses: ziishaned/jest-reporter-action@0.1.1
        with:
          test-command: "npm run test:coverage --watch=false --browsers=ChromeHeadless"

      # 6. Build library
      - name: Build project
        run: ng build percy

      # 7. Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          # name: build-${{ github.event.pull_request.number }}
          path: dist/percy
