name: Release

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

  workflow_dispatch:
    inputs:
      build_run_id:
        description: "ID Build Workflow"
        required: true
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts (manual execution)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/download-artifact@v4
        with:
          name: build
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run_id: ${{ github.event.inputs.build_run_id }}
          path: percy

      - name: List downloaded files
        run: ls -l percy

    # steps:
    #   # 1. Download build artifacts
    #   - name: Download build artifacts
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: build

    #   # 2. Configure Node.js
    #   - name: Setup Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 20

    #   - name: ls
    #     run: ls -l dist/percy

    # 3. Authenticate with npm
    #- name: Authenticate with npm
    #  env:
    #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # 4. Publicar en npm
    #- name: Publish to npm
    #  run: npm publish dist/percy
