name: Release

on:
  pull_request:
    types:
      - closed

  workflow_dispatch:

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true && contains(['main', 'release'], github.event.pull_request.base.ref) || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      # 1. Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      # 2. Configure Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ls
        run: ls dist/percy

      # 3. Authenticate with npm
      #- name: Authenticate with npm
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 4. Publicar en npm
      #- name: Publish to npm
      #  run: npm publish dist/percy
