name: Release

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

  workflow_dispatch:
    inputs:
      build_run_id:
        description: "ID Build Workflow"
        required: true
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Show workflow_run
        if: ${{ github.event_name == 'workflow_run' }}
        run: echo "BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      - name: Show workflow_run2
        if: ${{ github.event_name == 'workflow_run' }}
        run: echo "BRANCH=${{ github.event.repository.default_branch }}" >> $GITHUB_ENV

      - name: Download artifacts (from automatic execution)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: build
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          path: percy

      - name: Show Run number
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "BUILD_RUN_ID=${{ inputs.build_run_id }}" >> $GITHUB_ENV

      - name: Download build artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: dawidd6/action-download-artifact@v7
        with:
          name: build
          path: percy
          workflow: build.yml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          run_number: ${{ inputs.build_run_id }}

      # - name: Download build artifacts (manual execution)
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build
      #     github-token: ${{ github.token }}
      #     repository: ${{ github.repository }}
      #     run-id: ${{ inputs.build_run_id }}
      #     path: percy

      - name: List downloaded files
        run: ls -l percy

    # steps:
    #   # 1. Download build artifacts
    #   - name: Download build artifacts
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: build

    #   # 2. Configure Node.js
    #   - name: Setup Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 20

    #   - name: ls
    #     run: ls -l dist/percy

    # 3. Authenticate with npm
    #- name: Authenticate with npm
    #  env:
    #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # 4. Publicar en npm
    #- name: Publish to npm
    #  run: npm publish dist/percy
