name: Release

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

  workflow_dispatch:
    inputs:
      build_run_id:
        description: "ID Build Workflow"
        required: true
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Validar la rama (solo para ejecución automática)
      - name: Validate branch (automatic execution)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/github-script@v6
        with:
          script: |
            const ref = github.event.workflow_run.head_branch;
            if (ref !== 'main') {
              throw new Error(`Build run is from branch '${ref}', not 'main'. Exiting.`);
            }
            console.log(`Validated branch: ${ref}`);

      # 2. Descargar artefacto automáticamente (solo para ejecución automática)
      - name: Download artifacts (from automatic execution)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/download-artifact@v4
        with:
          name: build

      # 3. Descargar artefacto manualmente al especificar un run_id
      - name: Set run_id for manual execution
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build_run_id != '' }}
        run: echo "BUILD_RUN_ID=${{ github.event.inputs.build_run_id }}" >> $GITHUB_ENV

      - name: Fetch artifacts from specific Build run
        if: ${{ github.event_name == 'workflow_dispatch' && env.BUILD_RUN_ID != '' }}
        uses: actions/github-script@v6
        with:
          script: |
            const runId = process.env.BUILD_RUN_ID;
            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            const ref = workflowRun.data.head_branch;
            if (ref !== 'main') {
              throw new Error(`Build run is from branch '${ref}', not 'main'. Exiting.`);
            }
            console.log(`Validated branch: ${ref}`);

      - name: Download build artifacts (manual execution)
        if: ${{ github.event_name == 'workflow_dispatch' && env.BUILD_RUN_ID != '' }}
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: List downloaded files
        run: ls -l dist/percy

    # steps:
    #   # 1. Download build artifacts
    #   - name: Download build artifacts
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: build

    #   # 2. Configure Node.js
    #   - name: Setup Node.js
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 20

    #   - name: ls
    #     run: ls -l dist/percy

    # 3. Authenticate with npm
    #- name: Authenticate with npm
    #  env:
    #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # 4. Publicar en npm
    #- name: Publish to npm
    #  run: npm publish dist/percy
